name = "lms-stats"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[ d1_databases ]]
binding = "DB" # available in your Worker on env.DB
database_name = "lms-stats"
database_id = ""

[[ kv_namespaces ]]
binding = "QC"
id = ""
preview_id = ""

# The rate limiting API is in open beta.
[[unsafe.bindings]]
name = "STATS_UPDATE_LIMITER"
type = "ratelimit"
# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.
namespace_id = "3483"

# Limit: the number of tokens allowed within a given period in a single
# Cloudflare location
# Period: the duration of the period, in seconds. Must be either 10 or 60
simple = { limit = 1, period = 60 }